function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "No"};
	this.sidHashMap["No"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Fenice_VehicleModel:5850"};
	this.sidHashMap["Fenice_VehicleModel:5850"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S1>/driver_request"] = {sid: "Fenice_VehicleModel:5851"};
	this.sidHashMap["Fenice_VehicleModel:5851"] = {rtwname: "<S1>/driver_request"};
	this.rtwnameHashMap["<S1>/u_bar"] = {sid: "Fenice_VehicleModel:5852"};
	this.sidHashMap["Fenice_VehicleModel:5852"] = {rtwname: "<S1>/u_bar"};
	this.rtwnameHashMap["<S1>/omega_rr"] = {sid: "Fenice_VehicleModel:5853"};
	this.sidHashMap["Fenice_VehicleModel:5853"] = {rtwname: "<S1>/omega_rr"};
	this.rtwnameHashMap["<S1>/omega_rl"] = {sid: "Fenice_VehicleModel:5854"};
	this.sidHashMap["Fenice_VehicleModel:5854"] = {rtwname: "<S1>/omega_rl"};
	this.rtwnameHashMap["<S1>/Omega"] = {sid: "Fenice_VehicleModel:5855"};
	this.sidHashMap["Fenice_VehicleModel:5855"] = {rtwname: "<S1>/Omega"};
	this.rtwnameHashMap["<S1>/delta"] = {sid: "Fenice_VehicleModel:5856"};
	this.sidHashMap["Fenice_VehicleModel:5856"] = {rtwname: "<S1>/delta"};
	this.rtwnameHashMap["<S1>/Brake"] = {sid: "Fenice_VehicleModel:6592"};
	this.sidHashMap["Fenice_VehicleModel:6592"] = {rtwname: "<S1>/Brake"};
	this.rtwnameHashMap["<S1>/Buffer"] = {sid: "Fenice_VehicleModel:5857"};
	this.sidHashMap["Fenice_VehicleModel:5857"] = {rtwname: "<S1>/Buffer"};
	this.rtwnameHashMap["<S1>/Bus Creator"] = {sid: "Fenice_VehicleModel:5858"};
	this.sidHashMap["Fenice_VehicleModel:5858"] = {rtwname: "<S1>/Bus Creator"};
	this.rtwnameHashMap["<S1>/Max motor torque"] = {sid: "Fenice_VehicleModel:5859"};
	this.sidHashMap["Fenice_VehicleModel:5859"] = {rtwname: "<S1>/Max motor torque"};
	this.rtwnameHashMap["<S1>/Terminator"] = {sid: "Fenice_VehicleModel:5860"};
	this.sidHashMap["Fenice_VehicleModel:5860"] = {rtwname: "<S1>/Terminator"};
	this.rtwnameHashMap["<S1>/Terminator1"] = {sid: "Fenice_VehicleModel:5861"};
	this.sidHashMap["Fenice_VehicleModel:5861"] = {rtwname: "<S1>/Terminator1"};
	this.rtwnameHashMap["<S1>/Terminator2"] = {sid: "Fenice_VehicleModel:5862"};
	this.sidHashMap["Fenice_VehicleModel:5862"] = {rtwname: "<S1>/Terminator2"};
	this.rtwnameHashMap["<S1>/Terminator3"] = {sid: "Fenice_VehicleModel:5863"};
	this.sidHashMap["Fenice_VehicleModel:5863"] = {rtwname: "<S1>/Terminator3"};
	this.rtwnameHashMap["<S1>/Terminator4"] = {sid: "Fenice_VehicleModel:5864"};
	this.sidHashMap["Fenice_VehicleModel:5864"] = {rtwname: "<S1>/Terminator4"};
	this.rtwnameHashMap["<S1>/Terminator5"] = {sid: "Fenice_VehicleModel:6593"};
	this.sidHashMap["Fenice_VehicleModel:6593"] = {rtwname: "<S1>/Terminator5"};
	this.rtwnameHashMap["<S1>/Tw"] = {sid: "Fenice_VehicleModel:5865"};
	this.sidHashMap["Fenice_VehicleModel:5865"] = {rtwname: "<S1>/Tw"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
